import asyncio
from sqlalchemy.future import select
from sqlalchemy import text
from app.database import AsyncSessionLocal
from app.models.sales import Lead, LeadActivity
from app.models.user import User

async def test_lead_creation():
    async with AsyncSessionLocal() as db:
        # First check if the tables and columns are all exactly what we expect
        res = await db.execute(text("SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'leads'"))
        cols = {row[0]: row[1] for row in res.fetchall()}
        print(f"Columns in leads table: {cols}")
        
        if not cols:
            print("ERROR: table 'leads' is completely empty or missing.")
            return

        # Fetch a user to act as tenant owner
        user_res = await db.execute(select(User).limit(1))
        user = user_res.scalars().first()
        if not user:
            print("No users found to act as tenant.")
            return
            
        print(f"Using user: {user.email} with tenant_id: {user.tenant_id}")
        
        try:
            new_lead = Lead(
                tenant_id=user.tenant_id,
                name="Test Lead Generated By Antigravity",
                phone="1234567890",
                location="Virtual City",
                interested_plan="Awesome Plan",
                assigned_agent_id=None,
                notes="This is a test to reproduce the 500 error",
                status="new",
                follow_up_at=None
            )
            db.add(new_lead)
            await db.flush()
            
            activity = LeadActivity(
                lead_id=new_lead.id,
                actor_id=user.id,
                action="created",
                note="Lead manually added to the pipeline."
            )
            db.add(activity)
            
            await db.commit()
            print(f"SUCCESS: Lead created successfully! ID: {new_lead.id}")
            
            # Clean up
            await db.execute(text(f"DELETE FROM leads WHERE id = '{new_lead.id}'"))
            await db.commit()
            
        except Exception as e:
            print(f"FAILED TO CREATE LEAD: Exception -> {e}")

if __name__ == "__main__":
    asyncio.run(test_lead_creation())
